config/routes.rb
Rails.application.routes.draw do
  resources :delivers
  
  root 'pages#home'

  get 'pages/about'

  get 'pages/location'

  get 'task/index'

  get 'task/create'

  get 'task/new'

  post 'delivers/done'

  post 'delivers/approve'

  post 'delivers/cancel'

  devise_for :users, :controllers => { registrations: 'registrations' }
  get 'pages/home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/deliver.rb
class Deliver < ApplicationRecord
    def self.to_csv(options = {})
        CSV.generate(options) do |csv|
          csv << column_names
          all.each do |product|
            csv << product.attributes.values_at(*column_names)
          end
        end
      end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/delivers_controller.rb
class DeliversController < ApplicationController
  before_action :set_deliver, only: [:show, :edit, :update, :destroy,:done, :approve, :cancel]

  # GET /delivers
  # GET /delivers.json
  def index
    @per_page = params[:per_page] || Deliver.per_page || 20
    @delivers = Deliver.all.paginate(:page => params[:page], :per_page => @per_page)
    respond_to do |format|
      format.html
      format.csv { send_data @delivers.to_csv }
    end
  end

  # GET /delivers/1
  # GET /delivers/1.json
  def show
    @user = User.all
  end

  # GET /delivers/new
  def new
    @deliver = Deliver.new
    @user = User.all
  end

  # GET /delivers/1/edit
  def edit
    @user = User.all
  end

  # POST /delivers
  # POST /delivers.json
  def create
    @deliver = Deliver.new(deliver_params)
    @user = User.all
    respond_to do |format|
      if @deliver.save
        format.html { redirect_to @deliver, notice: 'Deliver was successfully created.' }
        format.json { render :show, status: :created, location: @deliver }
      else
        format.html { render :new }
        format.json { render json: @deliver.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /delivers/1
  # PATCH/PUT /delivers/1.json
  def update
    @user = User.all
    respond_to do |format|
      if @deliver.update(deliver_params)
        Rails.logger.debug @deliver
        format.html { redirect_to @deliver, notice: 'Deliver was successfully updated.' }
        format.json { render :show, status: :ok, location: @deliver }
      else
        format.html { render :edit }
        format.json { render json: @deliver.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /delivers/1
  # DELETE /delivers/1.json
  def destroy
    @deliver.destroy
    respond_to do |format|
      format.html { redirect_to delivers_url, notice: 'Deliver was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def done
    @deliver.state = 'done'
    @deliver.save
    redirect_back(fallback_location: root_path)
  end

  def approve
    @deliver.state = 'approved'
    @deliver.save
    redirect_back(fallback_location: root_path)
  end

  def cancel
    @deliver.state = 'cancel'
    @deliver.save
    redirect_back(fallback_location: root_path)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_deliver
      @deliver = Deliver.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def deliver_params
      params.require(:deliver).permit(:name, :address, :objectlist, :is_deliverd, :driver, :approved, :state)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @delivers = Deliver.all
  end
  def about
  end
  def location
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

    private
  
    def sign_up_params
      params.require(:user).permit(:email, :name, :password, :password_confirmation, :role)
    end
  
    def account_update_params
      params.require(:user).permit(:email, :name, :password, :password_confirmation, :role, :current_password)
    end
  end

app/controllers/user_controller.rb
class UserController < ApplicationController
    # @user = User.find(params[:id])
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/delivers_helper.rb
module DeliversHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/delivers/_form.html.erb
<div class="col s6">
<%= form_with(model: deliver, local: true) do |form| %>
  <% if deliver.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(deliver.errors.count, "error") %> prohibited this deliver from being saved:</h2>

      <ul>
      <% deliver.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <label>Назва доставки:</label>
    <%= form.text_field :name, id: :deliver_name %>
  </div>

  <div class="field">
    <label>Кінцева адреса:</label>
    <%= form.text_field :address, id: "autolocation" %>
  </div>

  <div class="field">
    <label>Номенклатура:</label>
    <%= form.text_area :objectlist, class: "materialize-textarea" %>
  </div>
  <div class="field">
    <%= form.label 'Оберіть водія:' %>
    <%= form.select :driver do %>
    <% @user.each do |driver| %>
      <% if driver.role == 'driver' %>
      <%= content_tag(:option, "#{driver.name}", value: driver.id) %>
      <% end %>
    <% end %>
    <% end %>
  </div>

  <div class="field">
    <%= form.hidden_field :state, :value => 'pending' %>
    <!--<%= form.hidden_field :approved, :value => false %>-->
  </div>
  <br>
  <div class="actions">
    <%= form.submit "Створити Доставку", class: "waves-effect waves-light btn blue lighten-2" do %>
    <% end %>
  </div>
<% end %>
    <script>
    $(document).ready(function(){
      $('select').formSelect();
    });
    </script>

app/views/delivers/edit.html.erb
<h1>Редагувати:</h1>

<%= render 'form', deliver: @deliver %>

<br><br>

<%= link_to 'Показати', @deliver, class: "waves-effect waves-light btn blue lighten-2" %>
<%= link_to 'Назад', delivers_path, class: "waves-effect waves-light btn blue lighten-2" %>

app/views/delivers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Доставки</h1>

<% if current_user.role == 'driver' %>
<table>
  <thead>
    <tr>
      <th>Назва</th>
      <th>Адреса</th>
      <th colspan="3"></th>
    </tr>
  </thead>



  <tbody>
    <% @delivers.each do |deliver| %>
    <% if deliver.driver.to_i == current_user.id %>
      <tr class="<%= deliver.state == 'pending' ? 'blue lighten-2' : '' %> 
                 <%= deliver.state == 'done' ? 'blue-grey darken-1' : '' %> 
                 <%= deliver.state == 'approved' ? 'teal lighten-2' : '' %>
                 <%= deliver.state == 'cancel' ? 'red lighten-2' : '' %>">
        <td><%= deliver.name %></td>
        <td><%= deliver.address %></td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<% end %>

<% if current_user.role == 'operator' %>
<table>
  <thead>
    <tr>
      <th>Назва</th>
      <th>Адреса</th>
      <th>Водій</th>
      <th colspan="3"></th>
    </tr>
  </thead>



  <tbody>
    <% @delivers.each do |deliver| %>
      <tr class="<%= deliver.state == 'pending' ? 'blue lighten-2' : '' %> 
                 <%= deliver.state == 'done' ? 'blue-grey darken-1' : '' %> 
                 <%= deliver.state == 'approved' ? 'teal lighten-2' : '' %>
                 <%= deliver.state == 'cancel' ? 'red lighten-2' : '' %>">
        <td><%= deliver.name %></td>
        <td><%= deliver.address %></td>
        <td><%= User.find_by_id(deliver.driver.to_i).name %></td>
        <td><%= link_to 'Показати деталі', deliver,class: "waves-effect waves-light btn blue lighten-2" %></td>
        <td>
        <% if deliver.state == 'approved'%>
        <%= link_to 'Виконано', delivers_done_path("id"=>deliver), method: :post, class: "waves-effect waves-light btn blue lighten-2" %>
        <% end %>
        <% if deliver.state == 'cancel'%>
        <%= link_to 'Відмінити', delivers_done_path("id"=>deliver), method: :post, class: "waves-effect waves-light btn blue lighten-2" %>
        <% end %>
        </td>&nbsp;
        <td><%= link_to 'Редагувати', edit_deliver_path(deliver),class: "waves-effect waves-light btn blue lighten-2" %></td>
        <td><%= link_to 'Видалити', deliver, method: :delete, data: { confirm: 'Ви впевнені?' },class: "waves-effect waves-light btn blue lighten-2" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= render "shared/floating_button"%>
<% end %>

<% if current_user.role == 'accounter' %>
<%= link_to "Імпортувати таблицю", delivers_path(format: "csv"), class: "waves-effect waves-light btn blue lighten-2" %>
<%= select_tag :per_page, options_for_select([10,20,50], params[:per_page].to_i),
       :onchange => "if(this.value){window.location='?per_page='+this.value;}" %>
<table class="striped">
  <thead>
    <tr>
      <th>Ім'я</th>
      <th>Адреса</th>
      <th>Номенклатура</th>
      <th>Водій</th>
      <th>Статус</th>
    </tr>
  </thead>

  <tbody>
    <% @delivers.each do |deliver| %>
      <tr>
        <td><%= deliver.name %></td>
        <td><%= deliver.address %></td>
        <td><%= deliver.objectlist %></td>
        <td><%= User.find_by_id(deliver.driver.to_i).name %></td>
        <td><%= deliver.state %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

<br>

<%= will_paginate @delivers %>
<!-- <%= link_to 'New Deliver', new_deliver_path %> -->

app/views/delivers/new.html.erb
<h1>Нова доставка:</h1>

<%= render 'form', deliver: @deliver %>

<br>
<%= link_to 'Назад', delivers_path, class: "waves-effect waves-light btn blue lighten-2" %>

app/views/delivers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Назва:</strong>
  <%= @deliver.name %>
</p>

<p>
  <strong>Адреса:</strong>
  <%= @deliver.address %>
</p>

<p>
  <strong>Номенклатура:</strong>
  <%= @deliver.objectlist %>
</p>

<%= link_to 'Edit', edit_deliver_path(@deliver) %> |
<%= link_to 'Back', delivers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Delivery App</title>
    <%= csrf_meta_tags %>

    # <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    # <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCunL2-wTu_TVzO1lRRIyo-nth1v29MBtQ&libraries=places"></script>
    <script>
    $(document).ready(function(){
      $('select').formSelect();
    });
    </script>
  </head>

  <body>
    <%= render  "shared/navbar" %>

    <%= render 'shared/message' %>

    <div class="row">
    <div class="col m10 offset-m1">
    <%= yield %>
    </div>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/home.html.erb
<br>
<% if(user_signed_in?) %>
<div class="row">
<% if current_user.role == 'driver' %>
    <% @delivers.each do |deliver| %>
      <% if current_user.id == deliver.driver.to_i %>
        <div class="col s6 m6">
          <div class="card <%= deliver.state == 'pending' ? 'blue lighten-2' : '' %> 
                           <%= deliver.state == 'done' ? 'blue-grey darken-1' : '' %> 
                           <%= deliver.state == 'approved' ? 'teal lighten-2' : '' %>
                           <%= deliver.state == 'cancel' ? 'red lighten-2' : '' %>"> 
            <div class="card-content white-text">
              <span class="card-title"><%= deliver.name %></span>
              Номенклатура: <br/>
              <p><%= deliver.objectlist %></p>
              <hr>
              Адреса: <br/>
              <p><%= deliver.address %></p>
            </div>
            <div class="card-action">
            <% if deliver.state == 'pending' %>
              <%= link_to 'Взяти замовлення', delivers_approve_path("id"=>deliver), method: :post %>
            <% end %>
            <% if deliver.state == 'approved' %>
              <%= link_to 'Відмінити', delivers_cancel_path("id"=>deliver), method: :post %>
            <% end %>
            &nbsp;
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
<% else %>
  <script type="text/javascript">
    window.location.href="/delivers"
  </script>
<% end %>
</div>
<% else %>
<div class="row">
  <div class="col s12 m6">
    <div class="card red accent-2 darken-1">
      <div class="card-content white-text">
        <span class="card-title">Помилка!</span>
        <p>Для початку роботи потрібно ввійти</p>
       </div>
      <div class="card-action">
        <%= link_to  "Ввійти", new_user_session_path %>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/shared/_devisemes.html.erb
<% unless resource.errors.empty? %>
    <script>
        <% resource.errors.full_messages.each do |value| %>
            toastr.error('<%= value %>')
        <% end %>
    </script>
<% end %>

app/views/shared/_floating_button.html.erb
<div class="fixed-action-btn">
 <%= link_to new_deliver_path, :class => "btn-floating btn-large red blue lighten-2" do %>
  <i class="large material-icons">add</i>
 <% end %>
</div>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
    <script>
        <% flash.each do |key, value| %>
            <% type = key.to_s.gsub('alert','error').gsub('notice','success') %>
            toastr['<%= type %>']('<%= value %>')
        <% end %>
    </script>
<% end %>

app/views/shared/_navbar.html.erb
<nav>
    <div class="nav-wrapper blue lighten-2">
      <%= link_to "Доставка", pages_home_path, class: "brand-logo center"%>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <% if(user_signed_in?) %>
        <li>Ви ввійшли як <%= current_user.name %> |</li>
        <% if current_user.role == 'driver' %>
        <li><%= link_to "Таблиця", delivers_path%></li>
        <!--<li><%= link_to "Registrate New User", new_user_registration_path %>-->
        <% end %>
        <li><%= link_to "Вийти", destroy_user_session_path, method: :delete %></li>
        <% else %>
        <li><%= link_to "Ввійти", new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </nav>